name: 'Manage Tenants Action'
description: 'Track changes to tenants and dispatch dependant workflow'
author: 'Dysnix'

inputs:
  token:
    description: 'Global GitHub token with repo write access, can NOT use secrets.GITHUB_TOKEN!'
    required: false
  ref:
    description: 'Global reference of the workflow run. The reference can be a branch, tag, or a commit SHA'
    required: false
  repo:
    description: 'Global repo owner & name, slash separated, only set if invoking a workflow in a different repo'
    required: false
  pattern:
    description: 'Tenant file pattern for example live/{environment}/tenants.yaml'
    required: true
  mode:
    description: 'Tenant file mode plaintext or yaml (default: plaintext)'
    default: 'plaintext'
    required: false
  yaml-key:
    description: 'Path to tenants array (path.to.array)'
    required: false
  ignore-dispatch-on-file:
    description: 'Ignore operations when tenant file created/updated/deleted'
    required: false
  dispatch:
    description: 'Workflow dispactch rules (list of lines)'
    required: true

outputs:
  added-tenants:
    description: The list of tenants created (space separated)
  added-run-environments:
    description: The list of corresponding environments (space separated)
  added-run-ids:
    description: The list of corresponding dispatched workflows (space separated)
  removed-tenants:
    description: The list of tenants removed (space separated)
  removed-run-environments:
    description: The list of corresponding environments (space separated)
  removed-run-ids:
    description: The list of corresponding dispatched workflows (space separated)

runs:
  using: 'node12'
  main: 'dist/index.js'
